version: 0.2
phases:
  build:
    commands:
      - apt update
      - apt upgrade -y
      - apt install zip
      - echo "Running build"
      - zip -r scripts.zip ./scripts
artifacts:
  files:
    - scripts.zip
  name: test-artifact-$(date +%Y-%m-%d-%H-%M-%S)
