version: 0.2
phases:
  build:
    commands:
      - aws deploy push --application-name playground-aws-cicd --s3-location s3://test-cicd-artifact/artifact.zip --source scripts
artifacts:
  files:
    - '**/*'
  base-directory: scripts
