version: 0.2
phases:
  build:
    commands:
      - apt-get update
      - apt-get upgrade -y
      - apt-get install -y zip
      - zip -r scripts.zip ./scripts
artifacts:
  files:
    - scripts.zip
  name: test-artifact-$(date +%Y-%m-%d-%H-%M-%S)
